FROM    node

MAINTAINER username <username@example.com>

USER    node

ENV     HOME=/home/node/app

RUN     mkdir -p ${HOME} 

WORKDIR ${HOME}

CMD     ["echo", "Você deve criar seu próprio contêiner a partir deste."]

