FROM    node:8.17

MAINTAINER username <username@example.com>

ENV     NODEJS_VERSION=8.0 \
        HOME=/opt/app-root/src

RUN     mkdir -p ${HOME}

WORKDIR	${HOME}

CMD	["echo", "Você deve criar seu próprio contêiner a partir deste."]
